name: Testing

on:
  push:

jobs:
  testing:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: python -m unittest unit_tests.py